# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20161127_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=1, to='photos.Tag'),
        ),
    ]
