# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20161127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='pk', to='photos.Tag'),
        ),
    ]
