# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_auto_20161128_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'permissions': (('delete_post_perm', 'Delete Post'),)},
        ),
    ]
