# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_auto_20161128_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'permissions': (('can_delete_post', 'delete post'),)},
        ),
    ]
